---
- name: Install required packages
  dnf:
    name:
      - wget
      - tar
    state: present

- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-11.1.0.linux-amd64.tar.gz
    dest: /tmp/grafana.tar.gz

- name: Extract Grafana
  unarchive:
    src: /tmp/grafana.tar.gz
    dest: /opt/
    remote_src: yes
